### ISSUE TITLE
Лекция 2

### ISSUE THREAD

**Issue by MKondakova** [TonitaN/FormalLanguageTheory#1]
На странице 12 нужен знак пересечения
![image](https://user-images.githubusercontent.com/46626161/153046616-e110fbd3-d5d9-48f3-ba2d-f14e89c1bc91.png)

**Comment by TonitaN** [comment]
Спасибо! Исправлено:
34dd9ea1a212c9fb4df1e9641cec7d8c6c69511d
Заодно немного подорваны скрепы: определение альфа-преобразования перенесено из лекции 7 в лекцию 2, в которой оно используется как уже известное читателю.

**Comment by TonitaN** [comment]
Это обсуждение более не актуально, т.к. в новом учебном году лекции поменялись.
