### ISSUE TITLE
Вопросы по ЛР №4

### ISSUE THREAD

**Issue by boomb0om** [TonitaN/FormalLanguageTheory#10]

**Comment by pollykon** [comment]
Добрый день! Вопрос по доп заданию 1. Какая взаимосвязь между follow, first и firstk? не совсем понятен алгоритм.

**Comment by TonitaN** [comment]
Без `follow` не удастся построить `first` для грамматик с эпсилон-правилами. А дальше алгоритм для k=1 требуется обобщить на произвольное k.

**Comment by SoFa325** [comment]
Правильно ли я поняла, что функцию $First_k$ надо определять по аналогии с $First_1$, а не используя её?

**Comment by TonitaN** [comment]
Либо `First1` используется как каркас (т.е. расширяется), либо 

Были ещё вопросы по поводу левой рекурсии и по поводу `Follow_k` для циклических правил. 
Если есть леворекурсивное правило вида `A -> A B1 B2 ... Bn`, то по определению `first (A) = Union (first(A),first(A), if Nullable(A) then First(B1 ... Bn))` (аналогично можно сделать через follow). Объединение двух первых `first(A)` равно каждому из них, то есть леворекурсивный шаг ничего не даёт. Проще говоря, левую рекурсию в рекурсивном алгоритме можно игнорировать, если `A` не порождает эпсилон, и заменить правилом `A -> B1 B2 ... Bn` в противном случае.
Для `first_k` почти то же самое, только в роли эпсилон выступят слова длины до k-1 включительно, порождаемые языком нетерминала `A`.
Аналогично циклические правила для Follow: правила вида `A->A` можно вообще игнорировать, т.к. они сразу же стабилизируются по объединению.

Для примера разберем First2 для такой вот грамматики:
```
A -> A b B | B c | B
B -> A a B | a | B A
```
Первый шаг: 
```
First2(A) = пусто (все правила рекурсивно ссылаются на пустые множества, расширять нечего)
First2(B) = {a}
```
Второй шаг:
```
First2(A) = {a} (из 3 правила) U {ac} (из второго правила). Первое правило пока игнорируется, т.к. множество для А на первом шаге было пусто.
First2(B) = {a} U {ac} (из 1 правила) U {aa} (из 1 правила, т.к. в First2(A) есть a) U {aa} (из третьего правила)
```
Третий шаг:
```
First2(A) = {a, ac} U {ab} (из 1 правила) U {aa} (из 2 или 3 правила, т.е. в First2(B) есть aa)
First2(B) = {a, ac, aa} U {ab} (из 1 правила)
```
Дальше уже всё стабилизируется, множества вычислены. Они совпадают, что не удивительно, т.к. `A` и `B` взаимно леворекурсивны.

ACHTUNG! Кое-какие онлайн-калькуляторы считают не по этому алгоритму и левую рекурсию обрабатывать не умеют. Не надо быть как они )

**Comment by Qmask26** [comment]
Так а что там с микроконтроллерами то...

**Comment by TonitaN** [comment]
> Так а что там с микроконтроллерами то...

Подходим к столу Артема Юрьевича (за которым теперь я сижу, это напротив входа), берём микроконтроллеры (их три штуки там) и вылавливаем Посевина, чтобы он показал основы, как с ними работать. Как будет сделан этот шаг, мы с Данилой Павловичем поставим задачу на 5 Л.Р. Или вы сразу с 4-й хотите начать?

**Comment by Ankalot** [comment]
Вопрос по варианту 2 (mod 3): какой смысл при присоединении левого контекста делать как слева, если можно как справа?
![image](https://user-images.githubusercontent.com/74981478/208253023-2a04fd25-9ea1-4831-8b68-d63c74bc6c75.png)

**Comment by TonitaN** [comment]
В контексте конкретной лабы это может сэкономить 1 символ в длине, т.е. правило длины 4 во втором случае станет правилом длины 3 в первом. Вне контекста лабы оно не нужно.

**Comment by Qmask26** [comment]
Можно, пожалуйста, если еще не поздно, задание на микрокотнроллеры, желательно два. А то очень не хочется экзамен сдавать. Мне всего-то 19 баллов не хватает до автомата...

**Comment by TonitaN** [comment]
> Можно, пожалуйста, если еще не поздно, задание на микрокотнроллеры, желательно два. А то очень не хочется экзамен сдавать. Мне всего-то 19 баллов не хватает до автомата...

Эх, я была бы рада их дать, но при всей моей симпатии к вам, правила есть правила, и уже поздно (да и некогда) :( Я ещё в конце декабря уточнила у Д.П., контактировали ли вы, и услышав отрицательный ответ, поняла, что у вас не хватило времени :( Сдавайте РК-2, и заодно к экзамену подготовитесь. Почти автоматом отл же, что вы, на компромат не ответите, и полторы задачи не решите?

**Comment by Qmask26** [comment]
Надеемся на лучшее, готовимся к худшему
