### ISSUE TITLE
ЛР №5

### ISSUE THREAD

**Issue by TonitaN** [TonitaN/FormalLanguageTheory#12]
Варианты:

1. На двух человек: составить грамматику для описания модели "сущность-связь" и реализовать генератор диаграмм "сущность-связь" и реляционных диаграмм (в любом удобном формате) по данной грамматике. Если 4 человека: то реализовать ещё генератор таблиц кардинальности и таблиц ключей в latex и сразу же встроить все данные (диаграммы + таблицы) в общий исходник.
2. На двух человек: составить атрибутную грамматику для описания контекстно-свободных грамматик (с атрибутами `isReachable`, `isGenerating`, `isNonEmpty`) и реализовать генератор случайных грамматик в пользовательском синтаксисе. На троих-четверых: добавить атрибуты нетерминалов `isRegular`, `isLL1`, `isLR0`, `isGNF`(+1) и пользовательский атрибут вероятности (+1).
3. На двух человек: составить грамматику для описания PDA (атрибуты переходов: `isDeterministic`, `isStackIndependent`; атрибуты узлов: `isInitial`, `isFinal` (читаемые из входных данных), `isTrap`) в пользовательском синтаксисе и реализовать генератор графов PDA. +1 человек: добавить порождение разбора входного слова по данному PDA.
4. На двух человек: составить грамматику для описания MFA (атрибуты переходов: `isReading`, `isWriting` (читаемые из входных данных), `isDeterministic`, `isMemoryIndependent`; атрибуты узлов: `isInitial`, `isFinal` (читаемые из входных данных), `isTrap`) в пользовательском синтаксисе и реализовать генератор графов MFA. +1 человек: добавить порождение разбора входного слова по данному MFA.
5. На двух человек: составить грамматику для описания РБНФ в пользовательском синтаксисе и реализовать преобразователь из РБНФ в классическую КС-грамматику.

Если берёте один и тот же вариант, то только на разных языках.

**Comment by UsefulTornado** [comment]
Добрый день! Мы с Дмитрием Головкиным берём 5 вариант на питоне.

**Comment by p0rtale** [comment]
Берём с @Ankalot 2 вариант на lua.

**Comment by ynastt** [comment]
Мы с @pugprogram берем 5 вариант на С++

**Comment by TonitaN** [comment]
5 вариант могут взять ещё максимум одна группа либо больше, если на ФЯ (Haskell, рефал, Scala).

**Comment by nOmeep** [comment]
Мы с @N1X41 берем 5 вариант на Kotlin

**Comment by EliseySoft** [comment]
Беру 3 вариант на python’е с Козочкиным

**Comment by Pur3Vessel** [comment]
Мы с @JazZzik берем 3 вариант на lua

**Comment by Dibydo** [comment]
1 вариант на Java с @megamax625

**Comment by alien-agent** [comment]
Берем с @Kekega 3 вариант на Go

**Comment by pollykon** [comment]
А будет выложено более подробное задание? и если будет, то когда примерно?

**Comment by TonitaN** [comment]
Про атрибуты и входной синтаксис напишу подробнее чуть позже. Но фишка здесь в том, что во многом этот синтаксис определяете вы, поскольку именно вы составляете грамматику.

А вообще - на входе должно быть для варианта 1 -  описание объекта в выбранном вами синтаксисе, для 2 - описание пользовательского синтаксиса (в форме списка подстановок), а для 3-5 - объекта в пользовательском синтаксисе и синтаксис в форме списка подстановок.
На выходе - либо диаграмма в выбранном вами синтаксисе (варианты 1,3, 4), либо грамматика в пользовательском синтаксисе (варианты 2, 5). В 5 варианте синтаксис один для РБНФ и грамматик, просто для грамматик он беднее.

То есть вы берёте построенную вами грамматику, подставляете в неё символы конкретных синтаксических конструкций, и затем по результату парсите входную грамматику и строите требуемый объект. Считаем, что неоднозначностей разбора нет, а если они появляются, то объявляем об ошибке.

**Comment by pear2jam** [comment]
Добрый вечер, берем 4 на питоне с @Pug-coder

**Comment by EliseySoft** [comment]
Правильно ли я понимаю задание (3 вариант)?
Строится обыная КС грамматика (не какая-нибудь атрибутная) для описания ПДА. 
Входные данные парсятся по этой грамматике и строится визуальное представление этого ПДА. Еще можно реализовать "прогонку" какой-нибудь строки по этому ПДА.
Всё так? Я ничего не упускаю?

**Comment by TonitaN** [comment]
> Правильно ли я понимаю задание (3 вариант)? Строится обыная КС грамматика (не какая-нибудь атрибутная) для описания ПДА. Входные данные парсятся по этой грамматике и строится визуальное представление этого ПДА. Еще можно реализовать "прогонку" какой-нибудь строки по этому ПДА. Всё так? Я ничего не упускаю?

Вы забыли про условие, что синтаксис частично определяет пользователь. Развёрнутое условие лабы есть в файле репозитория.

**Comment by EliseySoft** [comment]
Можно ли использовать генератор парсеров для создания парсера описания PDA?
Можно ли сделать так, чтобы пользователь задавал значения параметров в конфигурационном файле (например в .ini), и парсить этот файл с параметрами с помощью сторонней библиотеки?
Просто, если все ручками писать, то получится костыльное колдовство с подставлением строк - а так что-то +- интересное и читаемое получится.

**Comment by TonitaN** [comment]
Я предполагала этот вопрос. Тогда ответ такой: если хотите не анализировать и не разбирать грамматики сами, то параметром должны являться не отдельные константы, а вся структура грамматики. И вы должны описать грамматику описания грамматик, допустимых для разбора PDA. Например, чтобы я могла группировать правила, относящиеся к одному состоянию, так:
```
q1 {
A, a -> AA, q1
A, b -> eps, q2
}
```
Если сумеете справиться с описанием метаграмматики и извлечением из неё семантики, тогда можно пользоваться какими угодно генераторами парсеров. Иначе получится ну уж слишком просто, т.к. в постановке задачи рассмотрен максимально примитивный вариант параметризации.

**Comment by boomb0om** [comment]
Подскажите, пожалуйста, генератор случайных грамматик (2 вариант) можно писать как угодно? Или стоит придерживаться какого-то стиля, каких-то ограничений?

**Comment by TonitaN** [comment]
С учётом того, что написано в слайдах - как угодно можно. Если захотите, сами добавите параметры для генерации помимо указанных там.

**Comment by Lasadaf** [comment]
Беру 1 вариант на Rust

**Comment by boomb0om** [comment]
Вопрос по доп. заданию по 2му варианту. Атрибутную грамматику достаточно написать в pdf файле? Или ее нужно реализовать в генераторе как-то?

**Comment by TonitaN** [comment]
В принципе, достаточно её написать. Кто делает через сторонние генераторы - вот им желательно встроить, если будут делать этот доп, т.к. там должны быть такие возможности.

**Comment by Pug-coder** [comment]
Вопрос по заданию 4.
В тз написано, что флаги isReading, isWriting задаются пользователем при объявлении автомата. Но разве они не должны определяться автоматически?
тогда распределение флагов следующее?:
- isReading, isWriting, isDeterministic, isMemoryIndependent, isTrap - вычисляется автоматически
- isInitial, isFinal - задается пользователем

Также можете, пожалуйста, скинуть теорию про MFA, не совсем понятно как он работает?

**Comment by TonitaN** [comment]
`isReading` и `isWriting` определяются исходя из флагов работы с памятью, т.е. если считываемый символ - число, то это `isReading` состояние, если хотя бы одна память открыта, то `isWriting`. В общем-то, это почти по входным данным, т.е. действительно можно вычислять автоматически, спасибо за поправку.

**Comment by pollykon** [comment]
Вопрос по 2 варианту. атрибут isNonEmpty означает, что правило не может порождать epsilon? или же что правило не пусто?

**Comment by TonitaN** [comment]
То, что нетерминал не порождает пустое слово.
