### ISSUE TITLE
Анонсы консультаций

### ISSUE THREAD

**Issue by TonitaN** [TonitaN/FormalLanguageTheory#19]
Чтобы не мусорить в темах лабораторных, анонсы теперь будут здесь.

Консультация - воспоминание (со времен ДМ) по базовым понятиям теории автоматов: детерминизм, детерминизация, устранение эпсилон-переходов и их интерпретация, а также простейший алгоритм минимизации - в понедельник 25 сентября с 12-30 до 13-30. Посещение рекомендуется прежде всего тем, кто всё забыл и даже не уверен, что может отличить НКА от ДКА - да и в этом случае, если пропустите, не страшно: всегда можно посмотреть индусов.

**Comment by TonitaN** [comment]
Пресловутый РК-1 будет в конце октября (скорее всего, 21-го, но возможно и 28-го). Однако те, кто обрадовались, что до него ещё месяц, забыли, что он будет по всему пройденному материалу, а в октябре это будут уже не регулярки. Регулярки уже всё (осталось порешать задачки на логику и полугруппы). 
Опыт показывает, что если анонсировать дополнительную консультацию "для тех, кто ничего не понимает", на неё придут кабановы с гасаевыми, что слабо поспособствует уменьшению числа двоек на РК. В связи в этим или 6, или 8 октября предлагается провести нестандартную консультацию: в формате пробной "половинки РК" (по регулярным языкам минус часть материала последней лекции). Час вы решаете выданные задачи сами (без моих подсказок и жертвы у доски), а потом подробно разбираем все непонятные места и баги в решениях с каждым пришедшим лично. Заодно будет стимул повторить детерминизацию ;)

**Comment by TonitaN** [comment]
Пробный РК для желающих будет 6 октября с 11 до 12 часов. Тип задач единственный: проанализировать на регулярность (всего их будет две, и только два варианта, т.к. это пробная версия). Но решать можно сразу многими способами, так, как и на реальном РК: за каждый дополнительный способ на РК будут начисляться отдельные баллы.
- если язык не регулярен, то леммой о накачке напрямую или почти напрямую, либо по классам эквивалентности, либо используя замыкания регулярных языков по операциям
- если язык регулярен - построением или ДКА, или регулярного выражения. НКА на этом этапе не оцениваются, но на РК будет дополнительный бонус: решение путём построения минимального НКА. 

Результаты сдаём, и дальше в субботу или в пятницу вечером можно прийти за подробным разбором вашей работы. Дополнительно, если успею, то решения задач будут подвешены в репозитории. 

Почему есть причина хорошо подготовить эту часть материала? Потому что это подстраховка на будущее. Жизнь показывает, что к моменту РК-2 очень многие "сходят с дистанции" и вынуждены сдавать ДЗ на минималках, причём ещё и решённые не совсем самостоятельно.  У большинства студентов шанс набрать баллы на РК - это именно РК-1, пока ещё нагрузка позволяет качественно подготовиться к решению всех типов задач и не увязнуть в огромном объёме материала. Был, конечно, и уникум, РК-1 едва не сдавший на двойку (спасла "жалкая регулярочка" на черновиках), а на РК-2 решивший почти всё и ставший почти лучшим. Но шанс, что это именно ваш случай, стремится к бесконечно малому эпсилон. А мне не интересно и неприятно ставить недопуски трём четвертям группы, поэтому уж лучше я потрачу дополнительное время на ТФЯ сейчас, чем в феврале-марте.

**Comment by TonitaN** [comment]
Ещё одно объявление для тех, кто проявил интерес к воркшопу по теории категорий. Тут лежит голосовалка с выбором дат воркшопа: https://github.com/TonitaN/Misc-Lectures/discussions/8

Приоритет голоса - у магистрантов, но если будет совсем не удобно, но хочется поучаствовать, то можно, например, записаться на один день из двух.

**Comment by TonitaN** [comment]
Дополнительный разбор алгоритмов третьей лабораторной: 16 октября с 12 до 13 часов (на 30 минут раньше обычного, чтобы не игнорировать возможно пришедших на консультацию курсовиков). 
Группа 51 ещё не знает, что на эту лабораторную будет выделен целый месяц до первого дедлайна, чтобы была возможность нормально подготовиться к РК.

**Comment by OkDenAl** [comment]
> Пресловутый РК-1 будет в конце октября (скорее всего, 21-го, но возможно и 28-го). Однако те, кто обрадовались, что до него ещё месяц, забыли, что он будет по всему пройденному материалу, а в октябре это будут уже не регулярки. Регулярки уже всё (осталось порешать задачки на логику и полугруппы). Опыт показывает, что если анонсировать дополнительную консультацию "для тех, кто ничего не понимает", на неё придут кабановы с гасаевыми, что слабо поспособствует уменьшению числа двоек на РК. В связи в этим или 6, или 8 октября предлагается провести нестандартную консультацию: в формате пробной "половинки РК" (по регулярным языкам минус часть материала последней лекции). Час вы решаете выданные задачи сами (без моих подсказок и жертвы у доски), а потом подробно разбираем все непонятные места и баги в решениях с каждым пришедшим лично. Заодно будет стимул повторить детерминизацию ;)

Здравствуйте! Подскажите пожалуйста когда у нас всё-таки РК (возможно, я прослушал) . 21го или 28го ?

**Comment by TonitaN** [comment]
28-го, конечно. Если бы 21-го, то я бы уже написала, какой будет тип задач, и объявила о консультации в конце прошлой недели.

**Comment by TonitaN** [comment]
Консультация к РК-1 - 23 октября, с 12-00, в аудитории 330аю, до 13-30.
Можно даже в 11-30 начать, если будут такие пожелания (сверху 13-30 точная граница, из-за infamous комиссий по компиляторам).

**Comment by TonitaN** [comment]
Для желающих посетить семинар по HoTT, краткий обзор базовых понятий можно сделать разве что в субботу, с 11 (но у вас же лекция в это время) или после 17-15.

**Comment by nchtlv** [comment]
Антонина Николаевна, добрый день!
Просим Вас провести консультацию в субботу с 11:00.

**Comment by TonitaN** [comment]
Завтра с 11 до 11-50 встречаемся в 330аю.
И тут же - ссылка на ТГ чат семинара:  https://t.me/HoTT_Cats

**Comment by TonitaN** [comment]
27 ноября с 12-30 до 13-30 консультация-выдача 4 лабораторной работы (формально - с субботы 1 декабря). 330аю, как обычно.

**Comment by TonitaN** [comment]
Добрый вечер! Должно быть расписание на кафедре. Она точно 12-го, кажется, в 12 часов (время могу попутать). Консультация для двух групп сразу.

**Comment by madinabltv** [comment]
Добрый день! мы посмотрели время консультаций:

у первой группы в 15:00
у второй группы в 16:00

Получается все приходим в 15:00?

**Comment by TonitaN** [comment]
Да, к 15 лучше всем, чтобы два раза не повторять и успеть разобрать больше типов задач.

**Comment by TonitaN** [comment]
Внимание! ИУ9-51! Аттракцион невиданной щедрости! В честь 13-го числа (значит, у деканата шаббат), а также чтобы уравнять вас в правах с ИУ9-52, имеющей чуть больше времени до обнуления - акция!

Кто не успел доделать бонусы к ЛР или сами ЛР, но допуск уже имеет, можете доделывать их ещё в воскресенье, и баллы за бонусы будут учтены в вашей итоговой оценке.

Но вы должны обязательно сказать на экзамене, что будете доделывать лабы, чтобы я оставила поле оценки пустым. И если вы пришлете серьезно забагованное решение в ночь на понедельник, то извольте - режим МАТ-а уже отключится, я сразу же выставлю ту оценку, которая была на момент сдачи экзамена. Поэтому тестируйте свои допы.

**Comment by TonitaN** [comment]
P.S. - Использование этой акции роняет вашу репутацию на 75 баллов, поэтому готовьтесь к курсовой по ТФЯ в 7 семестре.

**Comment by TonitaN** [comment]
Кто особенно меня интересует сегодня:
- @Blackdeer1524 - остались минимальные правки, но на двух РК. Очень жаль, что вы затягиваете с ними, с учётом списка ниже, это отнимет драгоценное время у других.
- @Encapsulateed - жду последнюю ЛР (можно воспользоваться акцией и сдать базу, а потом добавить нужный балл)
- @IOANNVOLZHSKIY - то же самое
- @affeeal - аналогично
- Богданов Павел, Перов Степан - жду РК2
- @ilyaaid - последняя ЛР

В моих интересах допустить как можно больше народа. Пожалуйста, давайте это станет нашим общим интересом, и тестируйте свои лабы перед отправкой, чтобы сэкономить то немногое время, которое у меня осталось на проверку ваших лаб до экзамена.

**Comment by TonitaN** [comment]
Порядок сдачи следующий.

В 6 утра я выкладываю список допущенных к экзамену. Затем вы до 10 утра организуете из допущенных группы по 5 человек. Первая группа подходит к 14, вторая - к 16, третья (буде она появится) - к 18 часам.
Если кто-то ещё допустится в течение утра, и в третьей группе будет недобор - придёт тоже к 18.

P.S. - @Sarah_Deep, если написать сообщение, а потом его удалить, то оно упадёт в уведомления тем, кто отслеживает репозиторий, а в публичном пространстве не останется.

**Comment by TonitaN** [comment]
@OkDenAl , вы можете по эпсилон-переходу "сдавать": в любое время вне записи.

**Comment by TonitaN** [comment]
Кто собирается ночью добивать допуск, отметьте, пожалуйста, смайлом это сообщение. Чтобы я знала, имеет ли смысл ложиться спать до 6 утра.

**Comment by TonitaN** [comment]
@Blackdeer1524, теперь только ваших накачек осталось дождаться.

**Comment by TonitaN** [comment]
Не 6 утра, но больше сдающих в ночи нет.
Поэтому обещанный список:
- Окутин (эпсилон)
- Киселев
- Афанасьев
- Куйвашев
- Слесарев
- Александрова
- Дужеева
- Алешин
- Андреева
- Булкин
- Локшин
- Новак
- И Перов и Богданов - вероятнее всего.

Кто-то должен идти на третий заход (13 человек, не считая человека-невидимку).

**Comment by TonitaN** [comment]
Итак, на часах 17:20, и ещё никто не ответил по билету... Идём на превышение рекорда прошлого года?

**Comment by TonitaN** [comment]
И всё ещё ни одного ответившего...

**Comment by klu4vanya** [comment]
не пугайте, пожалуйста 😭

**Comment by TonitaN** [comment]
Это коллективное сознание, я никого не заставляла откладывать ответ по билету)

**Comment by TonitaN** [comment]
В ведомости всё ещё только @OkDenAl  ....

**Comment by TonitaN** [comment]
@OkDenAl , ваша рекомендация оказалась неподходящей - из Сыто-Пьяно нас в прошлом году не выставили(

**Comment by Sarahdeep** [comment]
`Внимание анекдот:`
Приходит к священнику мужик и говорит, что исповедаться хочет. Священник спрашивает, что за грех у него. Мужик отвечает: — Вот пришёл один раз к другу, а его дома не было. Дверь мне его жена открыла, а тут как раз дождь начался, а у меня зонта не было, я остался, ну мы с ней и согрешили. Священник говорит: — Велик у тебя грех, но помолись, отпущу грех твой. — Но это ещё не всё. Пришёл я как-то к тестю, а его дома не было. Дверь мне тёща открыла, а тут как раз дождь начался, а у меня зонта не было, я остался, ну мы с ней и согрешили. — Этот грех ещё больше, Придётся тебе ещё больше молиться. — Но и это ещё не всё. Пришёл я как-то к тёще, а её дома не было. Дверь мне тесть открыл, а тут как раз дождь начался, а у меня зонта не было, я остался, ну мы с ним и согрешили. — Слышь, мужик, у тебя зонт с собой? — Нет. — Тогда п***дуй домой, а то вон дождь собирается.
<img width="344" alt="image" src="https://github.com/TonitaN/FormalLanguageTheory/assets/91503476/a64d6d7f-f13f-4ec6-9b0d-371eafc196ac">

**Comment by TonitaN** [comment]
Сегодня только до 4 утра, но ещё не вечер - 52Б, ждём.
(+ одна "неявка", уже ставшая классикой - в прошлый раз "неявочный" компенсировал до отла. @Blackdeer1524 , ждём вас на идрисе или с великолепными накачками)

**Comment by TonitaN** [comment]
Пыточный список на сегодня:
- @garryNeKasparov, @Sarahdeep - эпсилоны
- @ValeryPotrebina
- @vicadlsn
- @marcheanin
- @Tanya-g99
- @Sanyakamlg
- @01Time03Skipper02
Есть шанс:
- @Andrey-Karanik (нужно успеть проверить последнюю лабу)
- @madinabltv (целых две, но одна полупроверенная)
- Богданов Павел (если сам захочет + исправил компромат)

Лучше кому-то одному или двоим из главного списка подойти в 16, чтобы не ждать очереди восемь часов.

**Comment by TonitaN** [comment]
17:21, и никто ещё даже не пошёл отвечать. Новый народный вид спорта - развитие выносливости для ультра-марафона по тфя?

**Comment by TonitaN** [comment]
Сегодня завершились в 3:00 в сыто-пьяно. 3:00+4:00 больше рекорда прошлого года. Надеюсь, традиция будет немонотонной, и это верхний предел. Обнуление будет сегодня днем.

**Comment by TonitaN** [comment]
Внимание сдающим ТФЯ 24-го! Сдвигаемся на 15-00, иначе не успеем принять все курсовые (рассчитано с поправкой на оптимизм четверокурсников).

И ещё одно важное объявление: если вы сдадите лабы/РК/курсовые позже чем 9 вечера 23 января, шанс проверить их резко падает (и приоритет будет однозначно у курсовых). После двух часов ночи 24 января - шанс проверки нулевой, я уже поеду в Москву в 4 утра, и дальше времени на проверку не будет.

**Comment by TonitaN** [comment]
Вот кто тормозил с лабами и рк до последнего дня, тот сам себе плохой человек. Т.к. курсовики тоже решили, что сдавать РПЗ в последний день - это норм, а у меня нет time-stop-а, чтобы обработать все запросы. Курсовики в приоритете, адьос!

P.S. - Список допущенных к пересдаче будет здесь не позже 12 часов ночи.

**Comment by TonitaN** [comment]
Расстрельный список 24 января, гарантированная часть:
- @Blackdeer1524
- Богданов Павел
- @madinabltv 
Дальнейший - в порядке FIFO на допроверку с поправкой на репутацию:
- @vyydra (последние фиксы по РК)
- @Vsevolond (допроверить один РК)
- @makezh (одна лаба)
- @Encapsulateed и @IOANNVOLZHSKIY (одна лаба)
- @BogdanTeryukhov (две ЛР, сданные раньше, но после бесконечного числа попыток)
- @nchtlv (шанс что-то успеть проверить крайне мал, с учётом очереди выше)

У меня ещё остались две дедлайнерские курсовые (из пяти, ахаха) на проверку, после них начну проверять очередь, если время останется. Также какую-то часть очереди (не больше двух-трёх человек) смогу принять после раздачи билетов гарантированной части. Если вас в списке выше нет, значит, ваши шансы допуститься и сдать завтра равны нулю.

Но курсовые всё равно приоритетнее: это та их часть, которая сама выбрала такую долю. Если кто-то из вас добровольно решит писать курсач по ТФЯ, то тоже сможет абьюзить третьекурсников сдачей курсовой в последний день, дабы они знали, как плохо сдавать лабы в последний день.

**Comment by TonitaN** [comment]
WIN! Курсачи рассмотрены. Через 20 минут начинаю проверку очереди (час на вас остался).

**Comment by TonitaN** [comment]
Новости от @makezh и из чатика с @Encapsulateed:
- следующая пересдача - 5 февраля (курсовики тоже обязательно будут, они уже готовятся к засаде)
- в связи с объединением хвостовой и комиссионной сессии, обнулённые лабы стоят полный балл до 7 февраля (начало учёбы) + ещё 7 дней (по срокам прошлых хвостовых, даже с запасом). Потом коллапсируют в 5 баллов базы.

**Comment by TonitaN** [comment]
Одна интересная личность всё ещё решает РК, а вторая программирует на Идрисе... 1:10 ночи, мы в Бауманке, челлендж "тфя заменяет сон" продолжается.

**Comment by TonitaN** [comment]
Интересная личность номер 1 допустилась до экзамена и взяла билет, личность номер два - настраивается на экзамен по БД методом багфикса в IO-монадах. До открытия метро ещё три часа...

**Comment by TonitaN** [comment]
Ночной приём тфя был последним в эту сессию: традицию прекращаем, потому что в Час Быка оценки по тфя иногда начинают превращаться в оценки по другим предметам...

**Comment by TonitaN** [comment]
Расстрельный список на 5 февраля (расширяющийся):
- @vyydra
- @emrzvv
- @BogdanTeruykhov
- @Blackdeer1524 (эпсилон 👀🤡🌈)
- TBC

**Comment by TonitaN** [comment]
Всем, кто делает обнулённые ЛР и думает, что там всё решается в две строчки: возьмите пример с @geogreck, посмотрите, как другие делают фиксы в своих репозиториях, хотя бы тесты оттуда возьмите. А лучше - внимательно посмотрите на фиксы в коммитах (не все из них релевантны именно вашим вопросам, но какие-то - точно да). К сожалению, не везде есть issue на 130 сообщений, где подробно обсуждаются тесты и их последовательное преодоление, но чужой опыт (особенно - истории успеха, т.е. зачёта) точно не повредит.

Лабы в целом не сложные, но не без подводных камней.

**Comment by TonitaN** [comment]
> Ночной приём тфя был последним в эту сессию: традицию прекращаем, потому что в Час Быка оценки по тфя иногда начинают превращаться в оценки по другим предметам...

Повторяю для тех, кто привык к аномально длинным экзаменам и хочет заскочить на экзамен после работы. Завтра вряд ли получится.

**Comment by TonitaN** [comment]
Важное уточнение - приходим к 10-30. Полчаса будет возможность позадавать вопросы по задачам, пока я не уйду на защиты курсовых.

**Comment by TonitaN** [comment]
Последняя регулярная пересдача - 17 февраля. По объёму потока - не исключено, что 16-17 февраля. Точное время и расстрельный список будут объявлены позднее.

Напоминаю, что 15 февраля произойдёт обесценка обнуления - обнулённые ЛР начнут стоить 5 баллов базово. Кто не воспользуется этим шансом, тот может решить проблемы с недобором баллов дополнительными заданиями к 3 и 5 ЛР, а также написанием лабораторных работ на Рефале. 

Комиссионные пересдачи будут проходить в ином режиме. Строго полтора часа на билет (билеты несколько облегчённые по сравнению с регулярными), нахождение в непосредственной близости от принимающего (в любой момент я могу посмотреть, что вы делаете на телефоне или ноуте), можно пользоваться любыми справочными материалами, но нельзя ни с кем переписываться - за это сразу же комиссионный неуд. Думать над ответами на дополнительные вопросы по билету долго не придётся - отвечаете в течение 10 минут или никогда.

**Comment by TonitaN** [comment]
Всем, кто готов допуститься до 17 февраля, рекомендую подготовиться к экзамену:
- выспаться и подготовить мозг к работе на максималках в течение долгого времени
- повторить расширенные операции с регулярными выражениями (lookahead-ы и шаффлы), особенно - если они были у вас в ЛР. Повторить алгебру регулярок (многие на этом теряются) и теорему Майхилла-Нероуда. Точные формулировки мне не интересны, каждый мыслит на своём языке, но вы должны понимать её связь со свойствами регулярных языков.
- повторить все базовые леммы о накачке (регулярная, КС, ДКС) и метод подмены. Если содержательно не уверены в том, что их поняли, то хотя бы проработать технику. По необходимости - взять консультации у своих или у курса старше (например, у @mathhyyn). Можно выписать все языки, для которых вы умеете их применять (особенно - метод подмены и ДКС-лемму), чтобы искать с ними сходство в ваших задачах.
- осмыслить примеры из лекций про конъюнктивные грамматики и про MFA. Если @Encapsulateed завершит дебаг ЛР5, можете воспользоваться его парсером конъюнктивных грамматик (но не верьте, не перепроверив). Посмотреть ещё раз на третью задачу в РК2 и понять, как наследуются и действуют атрибуты.
- повторить расширенную иерархию, под каждый фрагмент диаграммы подобрать пару примеров (типа: регулярный, но не LR(0); LR(0), но не LL, и т.д.). Эти примеры могут вас выручить в третьей задаче.

**Comment by TonitaN** [comment]
- *Почему так долго проверяются лабы?*

Сегодняшний пример:
- IDEA перестал видеть pom-файл, но нигде в конфигурации не пометил его как ignored. Всё перезаливать, пересобирать, наконец, убедиться, что файл в игноре. Ура, собралось, работает. В smt-модели нигде не сказано, какая переменная чему соответствует. Включаем телепатию, пытаемся угадать по значениям. Не получилось - ищем в коде, ура, вроде бы понятно.
- Лаба под bazel вроде собирается, но не работает. Пересобираем через cmake, ставим все недостающие либы, потому что кому-то очень нравится писать в стиле питона на плюсах. Пересобрали, поняли, что проблема с символом, завершающим ввод, исправили, включаем телепатию, как читать переменные в smt2-файле. Ура, проверено.
- "У меня же нет ошибки в модели, вот пример" - в приложенном примере откровенный дисбаланс скобок, человек даже не пробовал запустить z3. Тратим ещё 15 минут на то, чтобы подробно объяснить, в чём он неправ.
- Смотрим на время и понимаем, что сегодня больше ничего проверить не успеем. 

Это ни в коем случае не жалоба, но констатация факта - такими темпами всё проверяется не быстро. И не надо мне писать каждые полтора дня "а вы ещё не проверили?" - вы должны были прислать свои работы гораздо раньше, теперь моё время ограничено too much, и единственное, что я могу обещать - что проверю всё до пересдачи. А уж если вы там оставили баги типа незакрытой скобки или числа начальных доминошек от 0 до бесконечности - ну будет недопуск, надо было самим прочитать, что у вас вычисляется, прежде чем посылать на проверку.

**Comment by TonitaN** [comment]
Ориентировочное время начала марафона - 18-15 - 18-30.
Важно! Если вы ещё не допущены, но осталось совсем мало (фикс одной лабы) + ваша репутация нормальная, то приходите завтра к 9 утра - будете сдавать вторым потоком.

Если ваша репутация около нуля и вы опять прислали что-то в день экзамена - не удивляйтесь, если вас не проверят, и вы пойдёте на комиссионную сдачу.

**Comment by TonitaN** [comment]
Очередь на проверку ЛР и РК (четверокурсники временно исчезли):
- @nchtlv 
- @pank-art
- @pear2jam
- @pnkvenemy
- @nybc4ik
- @xb0yx2k20
- @stewkk
Если появится фикс, то до последних четырёх:
- @ShilovaMaria
Если придут с РПЗ, то в любое время дня и ночи и с наивысшим приоритетом:
- @zlatoivan
- @Robby-the-Paladin

**Comment by dak151449** [comment]
NII CHAVO 😁

**Comment by geogreck** [comment]
Первый ответ сегодня начался в 02:17. Динамика, конечно, отрицательная, учитывая все потери, которые были совершены к этому времени (три ноутбука и рассудок).

**Comment by zlatoivan** [comment]
Пришел с РПЗ.

**Comment by TonitaN** [comment]
Мы потеряли Гречко... :(

**Comment by TonitaN** [comment]
Комиссии по ТФЯ будут проходить в два приёма. Первый поток - 26 февраля, второй поток - 2 марта. Распределение, кто пойдёт сдавать 26 февраля, скину в субботу, и оно обжалованию не подлежит. Обе сдачи - комиссионные, но одновременно за всеми проследить я не успею, поэтому будете сдавать в два приёма.

**Comment by TonitaN** [comment]
🎉🎉🎉И напоследок - прекрасные новости! 🎉🎉🎉
Список Избранных (в Тетрадь Смерти) в этом году действительно впечатляет:
- @stewkk
- @Encapsulateed
- @IOANNVOLZHSKIY
- @katuuuu
- @pnkvenemy
- а также, вероятнее всего, @xb0yx2k20

С учётом кармических долгов @Dibydo и @Qmask26 , и возможно @Postlog , который только на днях вник в ТЗ по курсовой, получится, что остальным крайне маловероятно будет попасть на курсовую по ТФЯ случайным распределением. Ещё раз посмотрите на список этих героев и скажите им спасибо за то, что грудью встали на вашу защиту!

**Comment by TonitaN** [comment]
@stewkk @pear2jam @TSARukyanGT
Встречаемся завтра в 13-50 в преподавательской. Пишем билеты до 15-50.

**Comment by TonitaN** [comment]
Последний в этом году фестиваль тфя (в экспресс-режиме) - 2 марта с 13-20. Не обязательно для него иметь 42 балла, достаточно трёх каких-то лабораторных и двух РК.

**Comment by TonitaN** [comment]
Пользуясь случаем, передаю ещё один привет @Encapsulateed, который ухитрился ответить на компромат @stewkk по лабораторной работе, просто проходя (буквально минутку!) мимо.

**Comment by Encapsulateed** [comment]
Так это был компромат...

**Comment by TonitaN** [comment]
Вот из этого комментария:
https://github.com/stewkk/iu9-tfl/issues/1#issuecomment-1963022855
Регулярки упрощались в процессе взятия производных, а соавтор лабы и не заметил.

**Comment by TonitaN** [comment]
Сегодня комиссии по компиляторам прошли с 50% двоек.

Практические выводы для младшего курса:
- приходить только с запиской и утверждать, что код существует, но не предъявлять его = на комиссии по компиляторам с гарантией получить двойку
- присылать код в последний момент в наполовину сделанном виде и не суметь внести небольшие исправления за несколько часов = на комиссии получить двойку
- присылать код в последний момент в наполовину сделанном виде, суметь внести небольшие исправления за несколько часов и получить тройку, но не доделать в дальнейшем по обещанию (привет @PROCENTX123 , именно он должник) = обречь дальнейшие курсы на гарантированные двойки по курсовым по компиляторам, в случае, если код наполовину доделан (без дальнейших шансов на фиксы). Роман, если вы не выполните своё обещание, то это будет жесткий буллинг следующих за вами поколений, и именно вашим именем мы назовём принцип "без полного функционала курсовой - сразу двойка без разговоров".

**Comment by geogreck** [comment]
Ожидаем результаты комиссии по теории формальных языков..

**Comment by TonitaN** [comment]
Возник вопрос некоторых незамутнённых товарищей, кто интересовался, за что такая кара: без теста работоспособности кода не аттестовывать. Его следует адресовать тем вашим предшественникам, кто посчитал за героизм сдавать курсовые, вообще не делая бэкенд. Отношения между преподавателями и студентами строятся в том числе и на доверии, и раз подорванное, восстанавливается оно непросто. Тем более, у кого есть рабочий код, но он и вправду его забыл дома, найдёт способ за несколько часов его донести до почты.

**Comment by TonitaN** [comment]
> Ожидаем результаты комиссии по теории формальных языков..

Два неуда, увы. Хотелось бы оптимистичнее, но неспособность построить грамматику для `a^n b a^n` или ловушку в автомате убеждает в необходимости обратного...

**Comment by TonitaN** [comment]
Н-да, ряды избранных следующего года в перспективе грозят существенно сократиться. Хорошо, что таблица репутации у меня осталась, и можно присмотреть новый набор из тех, кто теперь там с нижнего края...
