### ISSUE TITLE
Допзадание 1

### ISSUE THREAD

**Issue by TonitaN** [TonitaN/FormalLanguageTheory#22]
**Задача**

На вашем любимом* языке программирования (среду и компилятор* разрешается варьировать, но совсем уж легаси брать не рекомендуется) написать синтаксически ошибочную программу, при разборе которой компилятор укажет ошибочной минимум одну строку, где ошибка отсутствует.

*любимый язык программирования - тот, на котором вы написали хотя бы одну ЛР по ТФЯ. Если вы не сдали ещё ни одной лабораторной, тогда тот, на котором будете их сдавать.
*компилятор - грубое сокращение для "модуль синтаксического анализа компилятора, IDE или интерпретатора"

- на минимум (одна дополнительная несуществующая ошибка) - 1 балл
- указана строка, где нет ошибки, и не указана та строка, где ошибка есть - 2 балла
- к каждой реальной ошибке, декларируемой компилятором, добавляется две или больше несуществующие, по совокупности минимум 4 несуществующие ошибки при максимум двух указанных верно, причём если используются две конструкции, порождающие ошибки, то это конструкции разнородные - 4 балла
- компилятор не указывает ни одной строки, где реально есть ошибки, но указывает как на ошибочные хотя бы на две строки, где ошибок нет - 6 баллов. Если удастся довести число фантомных ошибок до 7+, притом что компилятором не указывается ни одной реальной, и ошибки разнородные, зачту на 8 баллов.

**Дедлайн**

Строгий - 3 декабря. То есть после 3 декабря это задание стоит 0 баллов.

**Comment by TonitaN** [comment]
Кое-кто уже нафармил на этом задании 8 баллов.

**Comment by TonitaN** [comment]
Если вы сломали синтаксический анализатор в IDE-шке (заставили его подсвечивать ошибку, которой не было бы в компиляторе), и разобрались в механизме поломки, тоже могу зачесть за максимальный балл. При этом нужно будет создать багрепорт в соответствующем репозитории поддержки синтаксиса.

**Comment by emrzvv** [comment]
@TonitaN а если окажется, что такой баг уже зарепорчен? как правило, в таких репозиториях в ишьюс лежит по нескольку тысяч багов, отфильтровать и найти, есть ли подобный найденному, может быть проблематично...
