### ISSUE TITLE
Менторство

### ISSUE THREAD

**Issue by TonitaN** [TonitaN/FormalLanguageTheory#23]
В рамках *"искусственного повышения успеваемости по ТФЯ"(с)Известно-кто* и для лучшей мотивации подготовиться к РК-2 всем относительно успевающим (т.е. сдавшим хотя бы одну ЛР) разрешается взять "на поручительство" кого-нибудь из однокурсников (но я могу не разрешить вам этого делать, если мне покажется, что заявка чересчур искусственная).

- Если ваш подопечный получит на РК-2 9+ баллов, то вы получите 1 балл, и еще по 1 баллу за каждые его 2 балла сверх 9.
- При этом его компромат становится вашим компроматом (т.е. на экзамене я могу спросить вас по задачам как с вашего РК-2, так и с РК-2 вашего подопечного) - независимо от его результата на РК-2. 

Уже заявили себя как менторы:
- @geogreck для Вячеслава
- @ValeryPotrebina для Мадины

Если я кого-то забыла, напоминаем о себе.

**Comment by klu4vanya** [comment]
а возможно сделать так, чтоб если вдруг подопечный получает больше баллов, чем ментор, то ментор получает баллы за своего подопечного? и то же про компромат? то есть сделать взаимовыгодные отношения между ментором и подопечным. кто больше баллов на рк получает, тот и ментор

**Comment by madinabltv** [comment]
а можно быть подопечным и одновременно ментором для кого-то?
(или быть ментором для своего ментора)

**Comment by TonitaN** [comment]
Менторство и так даёт бонусы, если подопечный получает хорошую оценку (даже если сам ментор РК завалил). Но извините, за минимальные 6 баллов бонусов не будет.

**Comment by geogreck** [comment]
А мне всё нравится! Отличная система!

**Comment by TonitaN** [comment]
Ради вас стараемся.

**Comment by TonitaN** [comment]
> ###
> [Nov 25, 2023](#issuecomment-1826413273)

Конкретно вам - можно.

**Comment by madinabltv** [comment]
Беру в подопечные @ValeryPotrebina ✨

**Comment by TonitaN** [comment]
Ожидаем высоких результатов на РК...
