### ISSUE TITLE
Рубежный контроль II

### ISSUE THREAD

**Issue by TonitaN** [TonitaN/FormalLanguageTheory#25]
### Задачи и баллы на Рубежном Контроле II

Тип задач - единственный: проанализировать язык.

1. Если язык не КС, то:
- доказательство этого посредством леммы о накачке или иным способом - 3 балла
- построение MFA или ref-слова (общего вида), либо обоснование, что ациклического/детерминированного MFA не существует - 3 балла. 
- построение конъюнктивной грамматики (общего вида), либо обоснование, что линейной КГ (автомата Треллиса) не существует - 3 балла. Альтернатива последнему - обоснование, что и ациклического, и детерминированного MFA не существует. Ещё одна альтернатива - доказательство, что язык не является конечной конъюнкцией КС-языков.

Если вы не доказали, что язык не КС, но доказали, что это не детерминированный КС-язык, то вам будет засчитаны 2 балла. Если при отсутствии доказательств более сильных свойств вы доказали, что это не LL-язык или не real-time язык, то вам будет засчитан 1 балл. Доказательство нерегулярности стоит 0 баллов для этого случая. Также 0 баллов будут стоить доказательства более слабых свойств при наличии доказательства более сильного.

2. Если язык КС, но не детерминированный:
- предъявление любой КС-грамматики или PDA - 1 балл
- обоснование, что язык не детерминированный - 2 балла
- построение MFA или ref-слова (общего вида), либо обоснование, что ациклического/детерминированного MFA не существует - 3 балла
- построение линейной конъюнктивной грамматики либо автомата Треллиса, либо обоснование, что линейной КГ (автомата Треллиса) не существует - 3 балла.  Альтернатива последнему - обоснование, что и ациклического, и детерминированного MFA не существует. Ещё одна альтернатива - доказательство, что язык не является конечной коъюнкцией линейных КС-языков (т.е. таких, в правых частях правил которых может быть только один нетерминал).

Если в этом случае вы не доказали, что язык - недетерминированный, но доказали, что он либо не real-time, либо не LL, то получаете 1 балл вместо 2. Если вы не предъявили никакую грамматику и не доказали ничего, кроме нерегулярности (но нерегулярность доказана), тогда получаете 1 балл за всю задачу. Если нерегулярность доказана в дополнение к более сильному свойству (например, недетерминированности), либо при наличии КС-описания языка, то она стоит 0 баллов.

3. Если язык детерминированный КС, но не регулярный:
- предъявление DPDA - 2 балла
- доказательство, что язык не регулярный - 1 балл
- анализ языка на real-time свойство - 3 балла, если не real-time, и 2 балла, если real-time
- анализ языка на LL-свойство - 2 балла, если не real-time, и 3 балла, если real-time
- анализ языка на LR(0)-свойство (беспрефиксность) - 1 балл
(смысл условия в п. 2 и 3 - чтобы не было превышения 9 баллов по совокупности. Если решён только один пункт из них, то он засчитывается за 3 балла в любом случае)
 
Если в этом случае вы просто предъявили какой-то PDA или КС-грамматику, и честно отметили, что есть недетерминизм (не удалось построить именно DPDA), тогда вы получаете 1 балл вместо 2. Если построен NPDA, но утверждается, что это DPDA - 0 баллов.

4. Если язык регулярный:
- предъявление любого регулярного представления - 3 балла
- предъявление минимального НКА (с обоснованием) - 3 балла
- анализ языка на 1-однозначность (существование регулярки, для которой автомат Глушкова детерминирован) - 2 балла
- анализ на LR(0)-свойство (беспрефиксность) - 1 балл

Если вы здесь не смогли построить регулярку, но построили LL(1)-грамматику, то получаете 2 балла.

P.S. - Раньше тут было голосование за день проведения, но оно уже не актуально (+ сорвалась распределённая сдача), поэтому смайлы остались как символ всеобщего ликования перед уникальным РК, на котором можно набрать максимум 27 баллов. И да, кто делает домашнее задание - актуальны только пункты на первые 3 балла (без допов), и итоговый балл за ДЗ будет равен 7 баллам, если сдадите до НГ, и 6 баллам после.

**Comment by emrzvv** [comment]
@TonitaN а есть возможность сразу в формате дз писать?

**Comment by TonitaN** [comment]
Распределённая сдача - это сдача и 16-го, и 23-го (на ваш выбор). При этом отменяется подготовка к бигфарме, которая проводится в оставшийся из дней до 30-го.

Сразу в формате ДЗ можно, но зачем?

**Comment by TonitaN** [comment]
И да, я заскриню итоговый пул завтра в 12 ночи, чтобы методом Гречко голоса потом не обнулились, и все знали, кто как высказался.

**Comment by TonitaN** [comment]
Так, у нас проблема: не видны голоса сверх 10 (или кто-то знает, как их увидеть? - тогда проблемы нет). Если ни у кого не получается, то последним голосовавшим просьба переголосовать на следующем сообщении (например, на сообщении @Encapsulateed ). В принципе, по первой десятке видно, что пока выигрывает распределённая сдача, но некоторых активных разработчиков ЛР (например, @adderallbaby) я в ней не вижу, и их мнение может оказаться неучтённым.

**Comment by Kabane-UN** [comment]
В мобильном приложении GitHub видно все голоса.

**Comment by TonitaN** [comment]
В итоге, всё-таки победила распределённая сдача (хотя некоторые ваши одногруппники с высоким удельным весом голоса так и не высказались).

**Comment by Kabane-UN** [comment]
@TonitaN получается теперь нужно провести ещё одно голосование, чтобы вы знали сколько вариантов готовить на завтра?

**Comment by TonitaN** [comment]
Непредвиденные обстоятельства (болезнь преподавателя) решили всё за нас. Завтрашнее занятие вообще отменяется - рубежный контроль проводим 23-го.

**Comment by madinabltv** [comment]
Выздоравливайте скорее! 🥺❤️‍🩹

**Comment by OkDenAl** [comment]
Хорошо ! Поправляйтесь! 🙏

**Comment by TonitaN** [comment]
Условие 5 ЛР выложено. В принципе, я сегодня в МГТУ, и могу провести консультацию по 5 ЛР с 12-30 до 13-20 (и заодно всех заразить, кто ещё не переболел, чтобы к 23-ему было выживших поменьше). Дедлайн по 5 ЛР сдвигается в связи с экстренными событиями на 7 января.

**Comment by TonitaN** [comment]
Первое сообщение обновлено - теперь там описание разбалловки за задачи.

**Comment by TonitaN** [comment]
Ещё одно. Все, кто сдался заранее (сразу решил брать ДЗ), получат свои варианты уже после того, как их получат сдающие очно.

**Comment by TonitaN** [comment]
Из проверенных самые высокие:
- Шилова 19 баллов
- Кабанов 17 баллов
- Окутин 14 баллов
- Балтаева 12 баллов (счастливый вариант!) => +1 балл Лере за менторство (хотя я не уверена, что ментор был единственный)

Но контраст очень резкий: или много баллов, или незачёт (есть и исключения с 7-8 баллами).

И ещё проверены не все.

**Comment by madinabltv** [comment]
А Лере не 2 балла?(потому что за каждые 2 балла сверх 9 ещё 1 балл) 

Мадина aka выбиватель баллов 😅

**Comment by TonitaN** [comment]
Точно, 2 балла.

**Comment by TonitaN** [comment]
Всё проверено. @vicadlsn потеснила лидеров с 14 баллами. @WizardOfOz21 , вы сколько листов сдавали? Я нашла один, не подписанный (и если бы не наш разговор, я бы вообще не вспомнила, чей это). Там 2 задачи, первую вы решали?

**Comment by TonitaN** [comment]
P.S. - В битве полов со счётом 8/5 выигрывают девушки. Рекомендую парням воспользоваться преимуществом с лабами и переписать РК2 29-го на 10+. Мне кажется, в основном вы просто не поняли, как нужно было фармить баллы.
