### ISSUE TITLE
Подарок под ёлкой (РК или баллы?)

### ISSUE THREAD

**Issue by TonitaN** [TonitaN/FormalLanguageTheory#26]
Моё правило - каждый год поощрять хороших студентов, кто вовремя сдавал лабы (и не слишком забагованно). Сейчас проверяю РК и вижу, что некоторая доля этих товарищей неудачно написала РК-2 (упустив возможность набрать большое число баллов). В связи с этим есть два подарка на выбор:
- тем, кто сдал хотя бы две лабы вовремя, будет шанс переписать РК-2 на полный балл во время БигФармы. Этим могут воспользоваться даже те, кто сдал на зачёт (можно попытаться улучшить свой результат, выбран будет максимальный из двух, а не последний).
- либо как обычно: за каждую сданную в срок лабу добавляется 1 балл

И главное, вы можете сами выбрать, какой подарок возьмёте. У кого сдана только одна лаба в срок, вариантов нет - только второй (+1 балл).

И ещё. Поскольку некоторые менторы записались в таковые "потому что всё отлично, мне нравится" (да, я с самого начала понимала, что это несерьёзно, но вы же сами подписались, вас никто не заставлял, так что... it's a trap) - пока этот ментор не сдаст РК-2, бонусные баллы к НГ за подарок-2 проставлены в ЭУ не будут. Потому что серьёзнее надо относиться к обещаниям, а группа, ждущая своих баллов, некоторых личностей лучше мотивирует, чем угроза сдавать ТФЯ на комиссии.

P.S. - У кого в срок сдана одна лаба - вы ещё можете выйти в счастливчиков, сдавших 2 лабы вовремя, если сделаете ЛР 5 до фармы (первый кейс) или до 1 января (второй кейс).

**Comment by TonitaN** [comment]
@geogreck , вот зачем вы минусите сообщение с хорошими новостями? Или вам грустно, что кому-то подарки достанутся, а вам нет? Намного проще сдать РК и ЛР5 в срок и даже получить бонусные баллы, чем затягивать всё до весны.

**Comment by geogreck** [comment]
Не нравится, что чья-то судьба по тфя транзитивно зависит от крайне безотвественных людей, чьи перспективы довольно туманны

**Comment by TonitaN** [comment]
Требований минимум - сдать РК2 до официального экзамена (даже не до НГ, как я грозила вам лично). Вам же всё равно его сдавать придётся. Или не придётся?
Если сдадите до НГ, сделаете хорошим людям приятно, и стоить он будет 7 баллов, а не 6.

**Comment by TonitaN** [comment]
@Kabane-UN , можете приходить в понедельник с зачёткой - на CSY свойстве нафармили необходимое число баллов (хоть в 3 задаче и всё-таки я вам изначально правильную наводку про регулярку указала, недетерминизма там нет, но всё равно на автомат хватает).
