### ISSUE TITLE
Биг Фарма

### ISSUE THREAD

**Issue by TonitaN** [TonitaN/FormalLanguageTheory#27]
Биг фарма будет *29 декабря* (не 30 декабря, просьба сообщить всему потоку!), с 10 до 13 часов (аудитория 309ю). Если нужно сместить на с 9 до 12 часов, это тоже возможно, по вашему выбору.

В рамках биг-фармы можно переписать РК2 очно, но только тем, кто сдал хотя бы 2 лабораторные без просрочки. 5 лабораторная тоже учитывается. Либо тем, кто болел 23-го и не писал (Максим Кежаев, Егор, это касается вас - возможно, кого-то ещё, про кого я не знаю).

А завтра к 12-30 можно прийти для очного разбора задач с РК2. Будем разбирать 22 вариант.

**Comment by Encapsulateed** [comment]
А какие задачи будут на бигфарме?

**Comment by TonitaN** [comment]
По всем темам курса. Можете посмотреть фарму предыдущего года, чтобы прикинуть. В этом году чуть-чуть иные вариации будут, но в целом принцип тот же.

**Comment by TonitaN** [comment]
Экстра к 3 задаче 22 варианта разобрана (real-time DPDA + LL-свойство). Рекомендую посмотреть: при построении RPDA там используются некоторые общие приёмы, которые могут помочь решить задачи на фарме.

**Comment by nchtlv** [comment]
Антонина Николаевна, здравствуйте. Возможно ли участвовать в биг-фарме удаленно?

**Comment by TonitaN** [comment]
Да, можно, но проверяться дистанционщики будут в последнюю очередь (после всех очников).

**Comment by TonitaN** [comment]
https://docs.google.com/spreadsheets/d/1MabwlQ4J_ddKOJjlm-mOsYRBlcxstNhoOlrfBv27XXU/edit?usp=sharing
Тут бронируем задачи. Кто очно, бронирует у меня или Мадины.

**Comment by TonitaN** [comment]
Проверьте, пожалуйста, свои бонусные баллы и баллы за бигфарму. Ради того чтобы не портить праздник, выставила всем бонусы, не дожидаясь РК от @geogreck . Если он чувствует хотя бы каплю благодарности за это, надеюсь, сдаст РК до 7-го января. 

P.S. - Из вышедших за рамки нормы: Окутин 77 баллов, Гасаев 76 баллов, Федоров 71 балл (+9 компроматных).

**Comment by geogreck** [comment]
И вас с новым годом, Антонина Николаевна!

**Comment by TonitaN** [comment]
Операция по выезду из глухой глубинки в мороз завершена успешно. Сегодня всем постараюсь ответить (касается и курсовиков, некоторые из них тоже фолловят этот репозиторий).

**Comment by TonitaN** [comment]
@geogreck , взаимно! Подозреваю, что мы с вами будем виртуально вместе и на следующем НГ, в хорошем смысле (т.е. на курсовой, а не после академа).

**Comment by TonitaN** [comment]
Раз уж @geogreck сделал здесь поздравлялку, то - всех успешно завершивших курс хочу поблагодарить за труды.

Особый респект:
- @Kabane-UN, @wizardOfOz21 - за глубокое погружение. Ваши лабы войдут в историю ТФЯ и, может быть, кого-нибудь когда-нибудь ещё спасут.
- @adderallbaby - за то, что тащил свою группу вперёд всю первую половину курса. Очень жалею, что у вас не отличная оценка, в моих воспоминаниях должна была остаться именно она.
- @garryNeKasparov - за 9999% рефала, 9 задач по HoTT и загадочность.
- @sarahdeep - за рабский труд в первой лабе и стойкое преодоление трудностей с решением задач.
- всем, кого я тут не перечислила по имени, но кто достойно делал лабы и не заставлял меня перепроверять их по 5 раз - за самокомпроматы, честную рефлексию и уважение к моему труду.  
- всем, кого я тут не перечислила по имени, но кто собирал группы по подготовке к РК и помогал другим понять условия лабораторных - за менторство и ассистирование, видимое и невидимое.
- всем, кто писал и пишет на функциональных языках - потому что это красиво (и я всё ещё верю в @Blackdeer1524 и его зависимые типы).

Приятно было иметь дело. Не прощаюсь, но надеюсь, что "черные метки" получат лишь те, кто их добивался непосильными стараниями, а все остальные будут писать курсовые по интересам. Только, пожалуйста, не заваливайте курс по компиляторам, если получили или готовитесь получить отлично по ТФЯ - это тоже чёрная метка.
