### ISSUE TITLE
Постановка Л.Р. №2

### ISSUE THREAD

**Issue by TonitaN** [TonitaN/FormalLanguageTheory#3]
В процессе формулировки второй лабораторной работы (алгебра преобразований над автоматами) пришла к выводу, что было бы интересно сделать её в форме групповых проектов. Так работы на каждого члена команды получится меньше, чем при написании лаб в одиночку (не нужно каждому писать парсер, `show`-методы, или тривиальные методы типа удаления эпсилон-правил), а результат может получиться интереснее. Но командная работа имеет свои минусы, поэтому выношу вопрос на обсуждение с вами (заранее, т.к. выдавать лабу буду на следующем занятии).

Вопрос такой: готовы ли к лабораторной работе в форме проектов? Если готовы, то сколько будет групп и какого размера? Мне не интересно, чтобы было несколько дублирующих друг друга проектов, поэтому если группы разные, то и языки тоже разные, а если группа большая, то преобразований в итоговом проекте придётся тоже больше реализовывать. 

Для одиночек либо тех, кто не попадёт ни в один проект, будут индивидуальные лабы по вариантам. Это не значит, что вы не можете пользоваться наработками ваших товарищей из групп (например, спастить парсеры), пишущих на тех же языках, но основная задача у вас будет выглядеть иначе.

В группе потребуется как минимум капитан (дизайн структур данных + девопс, должен хорошо знать язык, на котором делается проект, и быть готовым ревьюить коммиты), три человека на реализацию преобразований и парсера и один дизайнер (отвественный за красивый вывод результатов). Итого минимум 5 человек. Можно больше - тогда и подзадач будет больше. Если совсем большая команда (от 8 человек), можно взять ещё тестировщика.

Группы можно делать интернациональные - совместные по потоку (51+52).

Кто хочет проекты, прошу отметиться здесь и определиться с командами. Опять-таки, остальные не волнуйтесь, без лаб не уйдёт никто, по вариантам тоже будут.

**Comment by xtoter** [comment]
Ребятами уже организовали команду "Чиполлино" (9 участников), для этой ЛР. Язык программирования: С++
Список участников 
*  [Белякова](https://github.com/SoFa325)
*  [Дельман](https://github.com/xendalm)
*  [Ильин](https://github.com/StarikTenger)
*  [Князихин](https://github.com/dak151449)
*  [Макаров](https://github.com/Robby-the-paladin)
*  [Терентьева](https://github.com/mathhyyn)
*  [Терюха](https://github.com/xtoter)
*  [Чибизова](https://github.com/alina8031)
*  [Шевченко](https://github.com/shevchenkokk1)

**Comment by EliseySoft** [comment]
Ребятами уже организовали команду "Сосисочная" , для этой ЛР. Язык программирования: Python
Список участников

- Мягких
- Пашкевич
- Козочкин
- Суханов
- Наумов
- Константинова
- Сайкин

**Comment by Qmask26** [comment]
Ребятами уже организовали команду "Комплексные козырьки" , для этой ЛР. Язык программирования: Python
Список участников:

- Проскурников
- Федоров
- Поршенко
- Ядрихинский
- Герман

**Comment by TonitaN** [comment]
Всё ок. Но если есть те, кто возражает (например, несколько претендентов на один язык), можете писать здесь, если не удастся решить вопрос иначе. Подумаем, как поступить.

Напоминаю, что только одна команда на один язык (т.е. считаем без учёта разделения на группы). Плюс групповой работы - бонус языка распространяется на всех, а также меньше работы на каждого. Но будет и минус - чтобы не получить штраф, нужно успеть свою часть за 2 недели, даже если другие тормозят (например, тот, кто пишет парсер). А капитан получит штраф за просрочку, равный максимальному штрафу членов его команды (но с возможностью компенсации выполнением дополнительного задания).

**Comment by TonitaN** [comment]
Если очень хочется, то по мейнстримовым языкам, на которых есть сданные первые лабораторные всех вариантов, можно команду до 11 человек. Как вы понимаете, часть подзадач в таких командах может быть с ней связана.

**Comment by TonitaN** [comment]
Вы можете сами решать, что переиспользовать в своих реализациях. Но список рекомендованных реализаций, полагаю, лучше сделать. Думаю, на этом курсе возражений по обмену лабами не будет ни у кого. У старшекурсников спросим про их лабораторные отдельно (вы можете сделать это и сами): надеюсь, ни @Perpure, ни другие, у кого были адекватные реализации, возражать не станут.

**Comment by ynastt** [comment]
Антонина Николаевна, а что означает "подробности ТА" в слайдах lab_tfl_2022_2.pdf ?

**Comment by TonitaN** [comment]
Это значит, что подробности to appear. У индивидуальных вариантов - уже. У групповых надеюсь успеть до конца ночи, но если нет - время отсчёта времени сдвинется на следующий день от того, когда они появятся.

Так же и индивидуальные варианты - считаем дедлайн +2 недели от завтрашней среды.
