### ISSUE TITLE
Зачётные мероприятия

### ISSUE THREAD

**Issue by TonitaN** [TonitaN/FormalLanguageTheory#9]
Зачётной будем считать неделю с 24 декабря по 31 декабря. И на ней можно будет отыграться за все прогулы в семестре, если вы по какой-то теме не успели проявить свою гениальность.

- 24 декабря будет биг-фарма (формат как в прошлом году) (очно-заочно) + грамматическая гонка (очно). Можно участвовать и там, и там, всё по желанию.
- На грамматической гонке будет 2 отделения: регулярки и грамматики. На скорость (от 1 до 7 минут на задачу) нужно будет писать регулярки или грамматики для несложных языков (но возрастающих в сложности с номером). Всего 5 задач в отделении, за каждую 1 или 2 балла, как итог только на гонке можно нафармить 15 баллов.
- С 24 до 31 декабря объявляется дикая охота: я выбираю от 5 до 10 жертв (лучших реализаций лабораторных работ, выложенных в открытом доступе). Дальше в течение 25 декабря автор лабораторки-жертвы пишет к ней нормальный readme (за бонус в размере 2 или 3 баллов), предполагающий легитимные способы использования реализации. С 26 до 31 декабря проходит собственно охота: можно искать баги и сообщать о них в репозитории реализации. Каждый найденный концептуальный баг стоит 1 балл. 

Концептуальный баг - это баг, указывающий на класс ошибочных тестов. Например, если грамматика с правилами вида `A -> A` завешивает программу, то таких грамматик можно написать хоть тысячу - концептуально они укажут на один и тот же баг.

Чтобы дедлайнеры не переживали насчёт биг-фарм и прочего, обнуление лабораторных работ с 1 по 3 я проведу 31 декабря.

**Comment by TonitaN** [comment]
### Что такое нормальный `readme` при подготовке к охоте за багами
*(напомню, он стоит 3 балла)*

1. Описание входного синтаксиса в РБНФ (нет, не вставкой слайда!) с примерами корректного (а можно и некорректного, при неочевидных ошибках) ввода. Если есть какие-то ограничения на входные данные, они должны быть указаны.
2. Описание параметров запуска (ключей, передачи ввода, и т.д.).
3. Описание результата: что должна возвращать программа по указанным входным данным и как это читать.

**Comment by TonitaN** [comment]
### Открываем охоту
Чтобы объявить о найденном баге в программе, нужно завести issue в её репозитории. Пожалуйста, прежде чем заводить issue с найденным багом, убедитесь, что этот баг не задокументирован. В большинстве случаев это означает, что вам нужно будет посмотреть свежие issue с охоты, но в случае последнего проекта придётся просматривать все незакрытые issue с пометкой `bug`. 
![183-duplicates](https://user-images.githubusercontent.com/13885019/209496719-39746785-9068-4206-bbfa-f15bcc7ef80e.png)

### Список жертв охоты на баги
1. [Унификация](https://github.com/boomb0om/FormalLanguageTheory/tree/main/lab1) и [ГНФ](https://github.com/boomb0om/FormalLanguageTheory/tree/main/lab3).
2. [Трансмоноид](https://github.com/N1X41/FLT/tree/main/Lab2)
3. [Кнут-Бендикс](https://github.com/UsefulTornado/Formal-Languages/tree/main/TRS_termination) и [ещё один трансмоноид](https://github.com/UsefulTornado/Formal-Languages/tree/main/transition_monoid)
4. [SLR-подгонка](https://github.com/Lasadaf/FLT_labs/tree/main/lab4_v0)
5. [AST + LL-преобразование](https://github.com/Ankalot/FLT-labs/tree/main/4)
6. [Ещё одна ГНФ](https://github.com/GorbatovNik/TFL-labs/tree/master/lab-3)
7. [Инфиксы регулярок](https://github.com/Pur3Vessel/Regular_infix)
8. [Много лаб из секретного портала](https://github.com/p0rtale/tfl-labs) --- пока без readme, поэтому пока нельзя тестировать
9. [Анализ и преобразование автоматов](https://github.com/StarikTenger/Chipollino)

**Comment by TonitaN** [comment]
✨Пока что три 90+, и это уже больше, чем в прошлом году!✨
А может быть и 5, если ещё некоторые личности (не будем называть, они и так про себя всё знают) сделают 5 лабу. Мечты... 💖

**Comment by TonitaN** [comment]
Если я кому-то не ответила по лабораторным или РК, пожалуйста, перешлите свои письма ещё раз (только проверьте, что новых ответов точно нет). Из-за очень большой рабочей переписки и плохой сортировки писем я могла случайно потерять ваши сообщения.

**Comment by TonitaN** [comment]
Конечно, более концептуально было бы обнулиться в новогоднюю ночь, но в новогодний вечер тоже неплохо. Ваши подарки :) получила, проверку сегодня или в ближайшие пару дней уже не обещаю.

**Comment by TonitaN** [comment]
Итоги охоты на баги:
- @furstepnik +3 (вот это я понимаю: пришёл в нужное время, точно рассчитал, что ему нужно, и получил требуемое)
- @pollyKon +1

Хотя там было значительно больше улова, причём отнюдь не только в парсере. Но это нужно было знать, что искать, а если нет желания разобраться, в чём заключается алгоритм, то и не будет понятно, где искать баг. 

Ну что ж, спасение утопающих - *теперь уже* дело рук только самих утопающих. Но так и быть, дам самый последний шанс набрать баллы (больше не будет, и так достаточно упущенных возможностей).

Вы можете записаться в добровольцы на тестирование Чиполлино (последний проект в списке охоты) в период от 10 января и до экзамена либо до 20 января, если вы не успеваете получить допуск к экзамену. Доброволец тоже получает балл за каждый найденный новый баг, но это уже значительно сложнее, с учётом того, что там большой бэклог. Однако это сильно проще, чем добирать недостающие два-три-пять баллов лабами, и поверьте, багов там как минимум с десяток найдётся. 
Других возможностей добрать баллы помимо лаб не будет: у дедлайнеров есть обнуленные три лабы без штрафов, да и последние две никто не запрещает сделать на Рефале. Ваша оценка собственной степени гениальности, очевидно, привела вас к выводу, что ТФЯ не физра, и этот предмет нетрудно будет закрыть за пару недель. Не буду врать, такое возможно, и оспаривать вашу самооценку я не буду, наоборот, порадуюсь, у кого и вправду получится. Удачи адреналинщикам 🔋

**Comment by TonitaN** [comment]
Список "избранных" пополнился господином Мягких. Я обязательно попробую взять себе всех троих на курсач по тфя в следующем году, раз они так неиллюзорно намекнули на это желание.

**Comment by TonitaN** [comment]
Поскольку дедлайнеры полагают свои интересы важнее интересов группы (не злить преподавателя перед экзаменом) и не читают условия дедлайнов, то в следующем году будет система репутации. За каждую лабу, сданную не в срок, и фикс, сделанный значительно позже анонса бага, репутация будет падать. И отвечать быстро, так, как хочется всем студентам, я буду только тем, чья репутация почти безупречна. Остальные будут сами виноваты: затянули, значит, никто им в выходные ночью или в дополнительное время и не обязан ничего проверять. Ни официально, ни морально. Максимальная задержка ответа также будет зависеть от репутации - чем хуже, тем больше.

**Comment by TonitaN** [comment]
Уж лучше как @Qmask26 , имея почти безупречную репутацию, честно пойти на пересдачу, потому что не успели досдать что-то небольшое, чем пытаться продавить свои интересы и сдать всё на свете в последние два дня. Первое заставляет уважать, второе - увы.

**Comment by TonitaN** [comment]
38 писем от вас с лабами, РК и фиксами за 2 дня. Зомби-апокалипсис с примесью человеческой крови :(

**Comment by TonitaN** [comment]
Группа 51, кто пересдаёт, приходим в четверг к 9 утра (уж ладно, не к 8-30). И обязательно с направлениями! Иначе мы не успеем с экзаменом - сегодня вышли из МГТУ через с трудом найденную незапертую дверь.

**Comment by TonitaN** [comment]
А мне предстоит освежить компроматы на тех, кто уже о своих узнал. И да, @Qmask26, никто из вашей команды не знал, как запускается ваша оболочка - это оказался самый непроходимый квест из всех.

**Comment by Qmask26** [comment]
Так в ридми написано же

**Comment by TonitaN** [comment]
Они не читали, а только из юнит-тестов всё запускали :( Даже не знали, как называются в интерпретаторе их собственные функции %)

**Comment by TonitaN** [comment]
Причём мне особенно нравится, когда на экзамене или РК кто-то внезапно делает "открытие года": мы запустили это в нашем проекте, и оно посчиталось, как ни странно, правильно.

**Comment by TonitaN** [comment]
Группа 52, у вас сдающих намечается около 16 человек. Имеет смысл сделать два захода (14 и 17), или все не против ради чувства локтя сидеть полные 8 часов в очереди? Полагаю, лучше первое, тем более, так будет возможность пересдать БД, кому актуально.

**Comment by TonitaN** [comment]
По поводу курсовых (частый вопрос): в 6 семестре у вас строго, без выбора, курсовая по БД. В 7 семестре по выбору ЧМ или конструирование компиляторов (в рамках которого также существует явление "курсач по тфя"). Вот тогда и вступит в силу избранность, если только за избранными не выстроится очередь из других научников (что вряд ли, да и зачем вам? я лучше). Но если вы будете вести себя скучно, положительно и не слишком пропадать, то ваша метка избранности уже не будет распространяться на ВКР. 
Особо избранные могут попробовать взять курсач по БД + тфя, Вишняков будет очень рад, но лично я не советую ~тем более под воздействием тфя-интоксикации от экзамена длительностью 20 часов~. И так в этом семестре кое у кого флеш-рояль с курсовой.

**Comment by TonitaN** [comment]
Внимание! Пересдача переносится на 1 февраля. У вас добавляются целых два дня на доделку обнулённых работ (которые в феврале будут стоить уже всего 5 баллов).

**Comment by TonitaN** [comment]
Ну вот, я предупреждала, что сдавать всё лучше вовремя, а потом у меня не будет времени. Кто прослушал это предупреждение, тому теперь придётся понервничать, и поверьте, я и сама не хотела бы вас так дёргать, но выбора у меня нет. Если бы я была на месте студента, тоже бы переживала из-за бесконечных переносов пересдач, поэтому проявляю максимальное сочувствие и стараюсь пойти навстречу в чём могу. 

Пересдача переносится на 7 февраля по форс-мажорным не зависящим от меня причинам и физической невозможности приехать в МГТУ до начала следующей недели.

Если у вас очень горит направление, то вы сами должны приехать в ИПС на этой неделе, и если у вас есть допуск, я приму экзамен. Для этого нужно написать мне за день до этого, чтобы я могла оформить вам пропуск.

**Comment by TonitaN** [comment]
Избранность 99 уровня во вкладке "темы дипломов" :

![The_Chosen_One](https://user-images.githubusercontent.com/13885019/216292840-42dee27c-b3fc-4844-b757-98414522feb3.png)

Причём взялось неизвестно откуда и неизвестно кто так нам удружил. Фатум...

**Comment by TonitaN** [comment]
Раз уж @Postlog своим "правом избранного" решил не пользоваться, была надежда, что их число сократится до двух... Но нет, @Dibydo дал понять, что он соскучился по острым ощущениям после летней практики. Ну отрефакторил бы не так откровенно, есть же специалисты, кто мог бы дать консультацию по грамотной обфускации чужого стиля, не попал бы в число избранных. Но такие прямолинейные признания в избранности я пропустить, увы, не могу.

**Comment by TonitaN** [comment]
Жёсткий таймер окончания сдачи завтра - 15-30. Извините, производственная необходимость.
Начинаем в 9-30, пишем билет 2 часа (не 4!) Если кто-то не успеет до 15-30, то пойдёт сдавать ещё с кем-нибудь когда-нибудь потом.

**Comment by TonitaN** [comment]
Последняя не комиссионная пересдача - ориентировочно 21 февраля. Возможны небольшие изменения.

**Comment by TonitaN** [comment]
Если я кому-то не ответила по лабам, самое время напомнить о себе.

Те, у кого сдача комиссионная, тоже могут приходить 21 февраля. В честь дня защитника отечества, я не буду ставить им двойки в направления (а вот у кого сейчас в ЭУ стоит НА и кто при этом уже сдавал экзамен - буду, и таких без направления принимать не стану).

**Comment by TonitaN** [comment]
Не знаю, зачем я это делаю, возможно, потому что мне действительно хочется узнать, сумеет ли кто-то преодолеть проклятье нуля баллов по ТФЯ и спастись, в стиле постмодерна, за секунду до взрыва, но желающие получить консультацию по рефалу могут это сделать 21 февраля после выдачи счастливых билетов. Посмотрим, поможет ли кому-нибудь бонус +4. Мой прогноз - нет, но было бы интересно ошибиться.

**Comment by igor-vgs** [comment]
Здравствуйте!

Это письмо адресовано тем, у кого ноль баллов или всем, кто готовится к
пересдаче?

С уважением,
Бахтин Игорь ИУ9-52Б



сб, 18 февр. 2023 г., 18:02 Antonina Nepeivoda ***@***.***>:

**Comment by TonitaN** [comment]
К тем, у кого баллов так мало, что либо нужно сдавать 5 лабораторных, либо нужно делать их с бонусом +4. Тем, кто перечислен сообщением выше, рефал уже точно не нужен - те из них, кто ещё не допущен (включая вас), тот всё равно может быть допущен и без него. И даже, как я надеюсь, на днях.

**Comment by not-Whale** [comment]
Во сколько 21 числа приходить на рефал?

**Comment by TonitaN** [comment]
Я бы очень хотела сказать, что к 9-15, но пока не знаю, успею ли к 9 добраться. Если пойму, что успею, сразу сообщу. Иначе только к 11-30 получится.

**Comment by TonitaN** [comment]
Консультация будет в 9-00 в 309ю (она, кажется, свободна первой парой). В 8-50 там же будет раздача билетов.

**Comment by TonitaN** [comment]
Небольшое послание для тех, кто испытывает ненависть к фиксам, перепроектированию и дебагу. В отличие от быстрого кодинга по образцу, ИИ этого не умеет и полностью никогда не сумеет (но неплохо усовершенствуется, с помощью обучения на формальных методах, о чём нужно помнить уже сейчас, чтобы была мотивация не халявить на дискретке и тфя). Вы уверены, что без умения разбираться в чужом (и своём) коде и исправлять его вы будете кому-нибудь нужны лет через 10?
